server:
  port: 8084

spring:
  application:
    name: notification-service

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest

  config:
    import: optional:file:../.env[.properties]

logging:
  level:
    root: INFO
    com.smarttracker: DEBUG
